server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: client
          uri: lb://CLIENT
          predicates:
            - Path=/api/{api-version}/clients/**
        - id: account
          uri: lb://ACCOUNT
          predicates:
            - Path=/api/{api-version}/accounts/**
        - id: record
          uri: lb://RECORD
          predicates:
            - Path=/api/{api-version}/records/**
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka